### ISSUE TITLE
Is there a way we can get the app details and usage info using the Python API?

### ISSUE THREAD

**Issue by jubins** [Clarifai/clarifai-python#103]
On my dashboard, I can see the App id, name, creation date and other information about my app. But through the API when I instantiate my clarifai app. I can see only 6 options available `solutions`, `public_models`, `concepts`, `inputs`, `models` and `workflows` as in the ClarifaiApp class below.
```
class ClarifaiApp(object):
  def __init__(self,
               app_id=None,
               app_secret=None,
               base_url=None,
               api_key=None,
               quiet=True,
               log_level=None):
    self.api = ApiClient(
        app_id=app_id,
        app_secret=app_secret,
        base_url=base_url,
        api_key=api_key,
        quiet=quiet,
        log_level=log_level)

    self.solutions = Solutions(api_key)
    self.public_models = PublicModels(self.api)
    self.concepts = Concepts(self.api)
    self.inputs = Inputs(self.api)
    self.models = Models(self.api, self.solutions)
    self.workflows = Workflows(self.api)
```

 How can I get all the below information that I see on my dashboard using the python api? and is there a way I can get usage as well?
Below is my dashboard:
![Screenshot from 2019-08-02 11-37-12](https://user-images.githubusercontent.com/18559677/62382156-fffc1b00-b51a-11e9-96fe-db58cf3c1d85.png)

**Comment by rok-povsic** [comment]
Hi @jubins ,

The easiest value to get is the `CUSTOM MODELS` one. This is `len(self.models.get_all(private_only=True))`.

The other values cannot be accessed with the Python client (or via the REST API endpoints using the Clarifai API key). Instead, you need to use the (currently undocumented) REST API part to first login to get the authentication token, and then to access `/apps` endpoints.

1. Login:

POST to `https://api.clarifai.com/v2/login`
```
{
    "email": "YOUR_EMAIL",
    "password": "YOUR_PASSWORD"
}
```

The session token is in the `session_token` response field.

2. The `/apps` endpoint:

Use the session token in the header `X-Clarifai-Session-Token`, in a GET `https://api.clarifai.com/v2/apps` request. The INPUTS and CONCEPTS values are in your app's `input_count -> processed` and `active_concept_count` fields.

3. The `/billing_usage` endpoint:

Send a GET request to `https://api.clarifai.com/v2/billing_usage` (it requires `X-Clarifai-Session-Token` as well).

**Comment by zeiler** [comment]
Hey @jubins I'm curous what you use case for seeing that information is through the API? 

We are currently thinking through new authentication in the API and want to make sure your use case is covered.

**Comment by jubins** [comment]
Hey @zeiler and @rok-povsic, thank you for providing the api endpoints and examples.
We are looking at ways to present to users, based on their role, what model
options should be available to them. The goal is to allow users to select their
desired app, and subsequently, to select models from the list of all custom
and built-in models in that app.

**Comment by jubins** [comment]
Hi @rok-povsic, just a follow-up question on the `/billing_usage` endpoint. What are the parameters for start and end dates?

I'm trying to make a request like in below screenshot, where I want to see usage from 2018 onwards 

![Screenshot from 2019-08-20 12-13-57](https://user-images.githubusercontent.com/18559677/63364696-1e984980-c344-11e9-96ee-9e95a221451e.png)

**Comment by rok-povsic** [comment]
Hi @jubins, I believe that currently the `/billing_usage` endpoint takes no input parameters, so it's not possible to get usage from a certain date onward. But let me make sure and I'll follow up.

**Comment by rok-povsic** [comment]
Hi @jubins, that's correct, the `/billing_usage` endpoint takes no parameters and is currently the only available billing usage endpoint.

**Comment by jubins** [comment]
Hi @rok-povsic, thanks for confirming and all the help on this. I'll close this issue now.
