### ISSUE TITLE
Sending file to api from Windows7 fails?

### ISSUE THREAD

**Issue by TuulaP** [Clarifai/clarifai-python#16]
Hi, just started to experiment with clarifai, but I've problems with Windows7 & python2.7.10

python --version
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

I've line like:
``` 
result = clarifai_api.tag_images([open(fullfilename)])
``` 

but the verbose msg from api is (with some extra debug prints:)

```
File exists?:  True
DEBUG, file used:  [<open file 'A:/temp/toka.jpg', mode 'r' at 0x0000000002904390>]
WARNING:clarifai.client.client:Could not open image file: 0, still sending to server.
Traceback (most recent call last):
  File "clar_koe.py", line 71, in <module>
    result = clarifai_api.tag_images([open(fullfilename)])
  File "A:\bin\anaconda\lib\site-packages\clarifai\client\client.py", line 259, in tag
    language=language)
  File "A:\bin\anaconda\lib\site-packages\clarifai\client\client.py", line 633, in _multi_data_op
    self._get_multipart_headers, post_data_multipart, url, kwargs)
  File "A:\bin\anaconda\lib\site-packages\clarifai\client\client.py", line 728, in _get_raw_response
    raise ApiError(response) # raise original error.
```
Even referring to file from current directory, without pathname doesn't work. 
File exists check uses os.path.isfile, which passes.  Via curl everything works ok for the same file and also if I give the image location via url. (Anyhow, I'd really need to use a local filename instead).

Api's error msg is just: 
"data 0 is not a valid because: Data is corrupt or data type is not supported.."

:coffee:

**Comment by lycaon824** [comment]
I'm experiencing the exact same issue.

Mike

**Comment by fivejjs** [comment]
I got the same issue. Then change to ubuntu and it succeeded. Guess from the curl request:
```
curl -H "Authorization: Bearer <access_token>" -F "encoded_data=@/Users/USER/my_image.jpeg" -F "encoded_data=@/Users/USER/another_image.jpeg" https://api.clarifai.com/v1/tag/
```
I think it is the path problem.

**Comment by fivejjs** [comment]
I double checked the issue and changed the image to upload. With Anaconda python 3.5.0 on windows 7 professional, it works fine now.

**Comment by statsfuntime** [comment]
I have exactly the same problem, using python 2.7.
Tried python 3.5 but it then throws up a different error: "POST data should be bytes or an iterable of bytes. It cannot be of type str."
So I used fullfilename.encode() to change the string to bytes, but still get the same error message. Went back to python 2.7 and tried the same, but same error.
Any idea?
Thanks,
Frank

**Comment by robertwenquan** [comment]
Sorry for the delayed response. Please try to stay away from Python 3.5. It's not fully tested and supported. We haven't used the library on Windows either internally. I am checking it and will get back to you soon.

**Comment by robertwenquan** [comment]
Hi All, 

Instead of passing open('filename') to the clarifai_api.tag_images(), please pass with open('filename', 'rb') . This works on my test environment. 

Again, thanks for the feedback and we will work on and fix this compatibility issue.

Thanks,
Robert

**Comment by robertwenquan** [comment]
Hi @statsfuntime @fivejjs @lycaon824 @TuulaP 

Instead of passing open('filename') to the clarifai_api.tag_images(), please pass with open('filename', 'rb') . This works on my test environment.

Again, thanks for the feedback and we will work on and fix this compatibility issue and make our api easier to use for every developer.

Thanks and Regards,
Robert
