### ISSUE TITLE
TQDM version

### ISSUE THREAD

**Issue by logan-markewich** [Clarifai/clarifai-python#187]
Is it possible to bump the tqdm version? Or at least somehow lessen the version restriction? 

Getting all kinds of conflicts in poetry because of the strict dependencies, another package needs `tqdm>=4.65.0`

**Comment by isaac-chung** [comment]
Hi @logan-markewich, thanks for your question! Would you mind sharing with the team which package you're using that has that requirement? Feel free to open a PR for this btw.

**Comment by logan-markewich** [comment]
Thank you @sainivedh !
