### ISSUE TITLE
Tagging celebrities and logos

### ISSUE THREAD

**Issue by gulopey** [Clarifai/clarifai-python#20]
Hello,

While testing out your application, our team noticed that your API does not identify celebrities or logos when uploaded. Is this purposefully done to avoid copyright issues? I would recommend adding this to the README as we were not able to find reference to this bug on your GitHub page or the Clarifai webpage.

Yousif

**Comment by zeiler** [comment]
Hello,

Thanks for reaching out. At this time we do not offer that in the repo. Stay tuned for future API releases for more new features and capabilities!
