### ISSUE TITLE
Please choose and declare a license

### ISSUE THREAD

**Issue by pschanely** [Clarifai/clarifai-python#22]
I don't see a license in any of the usual places.  Presumably one that allows us to use this in commercial software, right?

**Comment by cassidoo** [comment]
@pschanely You can definitely use our API for commercial software!  This is just a client for the API.
On developer.clarifai.com you can sign up for an account, and if you want more than a free account, you can buy more API credits per month: http://clarifai.com/pricing

**Comment by pschanely** [comment]
Thanks for the response @cassidoo !
However, I am doing an audit of the 3rd party libraries we use in our project; so I am inquiring about the license under which this client library is distributed.  Since it's on a public github repo, I presume that it's some open source license (BSD, Apache, LGPL, MIT, etc), but I cannot find a declaration in any of the typical places (a license.txt file, in the setup.py, and/or in a comment at the top of individual code files). 
Cheers!

**Comment by jjangsangy** [comment]
Bump on this issue, @cassidoo 

Also do not see a license on [PyPI](https://pypi.python.org/pypi/clarifai). This package also has no information regarding who wrote it or is maintaining it. Is this the official python client by clarafai?

If you guys could just add an `MIT` or `Apache` license I can offer to help improve it, but this package is becoming like radioactive for legal reasons

**Comment by zeiler** [comment]
Hey @jjangsangy thanks for reaching out. Just added Apache 2.0 license to the repo. Thanks for pointing this everyone!
