### ISSUE TITLE
Sample URL needs to be updated

### ISSUE THREAD

**Issue by jared-clarifai** [Clarifai/clarifai-python#29]
Right now it says 

http://www.clarifai.com/img/metro-north.jpg

but that switched to 

https://samples.clarifai.com/metro-north.jpg

Readme.md and client.py

@robertwenquan

**Comment by eric-horvat** [comment]
The same goes for the other two sample URLs in the readme
- http://www.clarifai.com/static/img_ours/autotag_examples/metro-north.jpg
- http://www.clarifai.com/static/img_ours/autotag_examples/dog.jpg

**Comment by robertwenquan** [comment]
Thanks so much for reporting the documentation issue. They are all corrected.
