### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by IgWod** [Clarifai/clarifai-python#32]
In first example for the Tag from URL there is double g at the end of the link to the image.

There is:
`result = clarifai_api.tag_image_urls('https://samples.clarifai.com/metro-north.jpgg')`
It should be:
`result = clarifai_api.tag_image_urls('https://samples.clarifai.com/metro-north.jpg')`

**Comment by robertwenquan** [comment]
Hi @IgWod 

Thanks for reporting the typo. I just corrected it.
