### ISSUE TITLE
Setup.py refers to nonexistent scripts dir

### ISSUE THREAD

**Issue by cralston0** [Clarifai/clarifai-python#35]
In https://github.com/Clarifai/clarifai-python/blob/master/setup.py#L20 :
```
    scripts=['scripts/clarifai'],
```
was added 2 days ago, and it breaks pip install (using a github URL git+git://github.com/Clarifai/clarifai-python.git instead of pypi, which was in the docs until... recently?) with:

```
    error: file '/tmp/pip-XCb1ev-build/scripts/clarifai' does not exist
```

**Comment by cralston0** [comment]
https://github.com/Clarifai/clarifai-python/commit/20de1b66a6a24316b724e11ad7400935239050b8#diff-04c6e90faac2675aa89e2176d2eec7d8 was where instructions changed.  So this isn't so much an issue to be fixed as it is a heads up to people including clarifai-python in their requirements.txt to update the URL there.

**Comment by robertwenquan** [comment]
@cralston0 Thanks for reporting the issue. 
It is fixed by adding the extra script. 

Could you kindly let me know what is the reason to prevent you from using the pip package? We would like to have the installation as convenient as possible without downloading the source code.

Thanks,
Robert

**Comment by cralston0** [comment]
The only reason was inertia -- we have a couple apps where it's specified using the Github URL and changing that one line requires a QA & release cycle.

**Comment by robertwenquan** [comment]
Got it, though I would still recommended using the latest pip package as that's supposed to be more stable than the github repo.
