### ISSUE TITLE
Clarifai's Python version requirement clashes with inquirerpy's

### ISSUE THREAD

**Issue by phdye** [Clarifai/clarifai-python#365]
+ poetry add --dry-run clarifai
Using version ^10.5.4 for clarifai

Updating dependencies
Resolving dependencies... (0.0s)

**The current project's Python requirement (>=3.7,<4.0) is not compatible with some of the required packages Python requirement:**
  **- clarifai requires Python >=3.8, so it will not be satisfied for Python >=3.7,<3.8**

**Because no versions of clarifai match >10.5.4,<11.0.0
 and clarifai (10.5.4) requires Python >=3.8, clarifai is forbidden.
So, because inquirerpy depends on clarifai (^10.5.4), version solving failed.**

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For clarifai, a possible solution would be to set the `python` property to ">=3.8,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

+ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by srikanthbachala20** [comment]
@phyde clarifai lib is already restricted only for Python >=3.8 and we have even specified inquirepy version in requirements. So, there is no clash unless you are using Python 3.7. So, can you elaborate the issue in more details.

**Comment by sanjaychelliah** [comment]
Hi @phdye . Based on the comment, this doesn’t seem to be relevant at the moment, so I’ll close it for now. Please feel free to reopen if it becomes necessary later.
