### ISSUE TITLE
The tests are failing specifically for the Windows build.

### ISSUE THREAD

**Issue by sanjaychelliah** [Clarifai/clarifai-python#378]
# Error logs:
https://github.com/Clarifai/clarifai-python/actions/runs/10670436615/job/29574440883

# Temporary Fix:
The Windows tests have been temporarily excluded.

**Comment by srikanthbachala20** [comment]
This issue is due to upgrade in protobuf version. After downgrading it, all the tests are working fine. To debug this I have used tmate - https://github.com/marketplace/actions/debugging-with-tmate
Ref - https://github.com/Clarifai/clarifai-python/pull/380
