### ISSUE TITLE
Assumption of resizing need/success if PIL module is available

### ISSUE THREAD

**Issue by berendo** [Clarifai/clarifai-python#40]
The client uses the importability of `PIL` as an indicator that it "can resize":

https://github.com/Clarifai/clarifai-python/blob/c411cc53261d41f3b9c7031223f4ea5386690dfc/clarifai/client/client.py#L7-L8

However, it uses "can resize" as an unconditional/non-overridable "should resize" here:

https://github.com/Clarifai/clarifai-python/blob/c411cc53261d41f3b9c7031223f4ea5386690dfc/clarifai/client/client.py#L537-L540

Alas, the underlying resizing that's attempted via `PIL` is totally broken if the files that are passed in are `file` objects encapsulating non-randomly-seekable pipes (which the module is perfectly capable of using otherwise). For applications where the resizing is dealt with externally, and the image data piped into the client, the unconditional nature of this additional resizing becomes a show-stopper.

It is especially surprising when previously-working code stops working merely due to the independent installation of `PIL` via `pip` for an entirely different purpose. As a workaround, doing:
```
import sys
sys.modules['PIL'] = None
```
_before_ this client module is imported "hides" `PIL` from it.

It would be very desirable to disable additional resizing via an explicit argument, probably to the constructor.

**Comment by robertwenquan** [comment]
@berendo Thanks for reporting the issue. And it's good to hear the use case of pass non-seekable streaming into the file object. I will take a look into this and fix it tomorrow.

By the way, I assume you have been using our api for some time. However this is our v1 api client which is about to be deprecated. May I ask your use case of the api? If it's about image tagging without multi-language, you might want to check the v2 api that has no dependency on the PIL.

**Comment by robertwenquan** [comment]
Hi @berendo. This issue should be addressed in v2.0.14 that was released a min ago.

Thanks again for reportnig the issue. I am closing the issue right now.
