### ISSUE TITLE
how to config on windows

### ISSUE THREAD

**Issue by Struggle-YD** [Clarifai/clarifai-python#41]
dear team,
  hello, i am a stranger on python , can you give me a detailed introduction how to config in windows?
 
best!

**Comment by robertwenquan** [comment]
Hi @Struggle-YD,

Sorry for the delayed response. 
Have you installed the package? Can you give me more details on how you installed it?

**Comment by robertwenquan** [comment]
Due to no response I am closing this "ISSUE". Please feel free to reach out to support@clarifai.com for question like this.
