### ISSUE TITLE
How to setup clarifai v2.0.14 in ubuntu

### ISSUE THREAD

**Issue by IpshitaC** [Clarifai/clarifai-python#42]
Hi!
I have successfully installed the clarifai client. However, when I run the clarifai config command, I get an error that clarifai is not a command. 

How can I fix this? Otherwise, how else can I set up my client id and client secret?

Thanks in advance

**Comment by robertwenquan** [comment]
@IpshitaC could u let me know how you installed the package?

**Comment by IpshitaC** [comment]
@robertwenquan I simply ran the command pip install clarifai==2.0.14 through the command prompt.
Is that incorrect?

**Comment by robertwenquan** [comment]
@IpshitaC yes that is what it is supposed to be. 
can you run `pip show -f clarifai` and let me see what it shows?

**Comment by robertwenquan** [comment]
and also `echo $PATH`

**Comment by IpshitaC** [comment]
Here is a screenshot of the output
![screenshot from 2016-12-07 21 43 53](https://cloud.githubusercontent.com/assets/18362353/20975749/65fffb56-bcc6-11e6-94e7-893cdd9202db.png)

**Comment by robertwenquan** [comment]
ok. It looks your PATH is somehow not correctly set. 
can you also `which python` and `echo $PYTHONPATH` for me? Your run env doesn't look right to me.

**Comment by robertwenquan** [comment]
It's recommended to use virtualenv to manage your packages. Check https://virtualenv.pypa.io/en/stable/userguide/

Once you enable the virtualenv, you need to `pip install clarifai` again, and then you should be able to use `clarifai configure`

**Comment by IpshitaC** [comment]
Hi this is the output
![image](https://cloud.githubusercontent.com/assets/18362353/20983182/7f538666-bce1-11e6-9796-333ef5503b08.png)

**Comment by robertwenquan** [comment]
ping @IpshitaC 

any luck setup the client?

**Comment by robertwenquan** [comment]
I am going to close this issue as this is not an actual issue. Ping me or shoot an email to support@clarifai.com if you need further assistance.
