### ISSUE TITLE
Inputs search does not return any scores

### ISSUE THREAD

**Issue by chrismbarnes** [Clarifai/clarifai-python#43]

**Comment by robertwenquan** [comment]
Hi @chrismbarnes 

This will be in the v2.1.x client.

**Comment by chrismbarnes** [comment]
Thanks @robertwenquan, any idea when the v2.1.x will be pushed out?

**Comment by robertwenquan** [comment]
Hi @chrismbarnes 

the v2.0.20 has the score as one attribute of the Input()

you can get input.score to get the score of the search candidate.

Thanks again for reporting this issue and your patience for waiting so long. I am closing the ticket. 

Feel free to send me feedback if you have any.
