### ISSUE TITLE
Will clarifai.rest.ClarifaiApp v2.0.14 support application's "Default Language" option?

### ISSUE THREAD

**Issue by koitaroh** [Clarifai/clarifai-python#44]
Currently clarifai.rest.ClarifaiApp (v2.0.14) doesn't seem to support the "Default Language" option in "Manage Your Applications" page, while clarifai.client.ClarifaiApi does. ClarifaiApp always returns class names in English with the `predict_by_url` method.
Will clarifai.rest.ClarifaiApp v2.0.14 support application's "Default Language" option? (I would appreciate any tentative schedule.)

**Comment by robertwenquan** [comment]
Hi @koitaroh 

v2.0.x v2 api does not support multi language. 

If you want to use multi-lang feature, you will have to use the v1 api. It's clarifai.client.ClarifaiApi and the v2.0.x client is fully compatible with the v1 api. 

I will let you know when we add multi language in the v2 api.

**Comment by koitaroh** [comment]
I see. Thank you. I always appreciate your good work.

**Comment by robertwenquan** [comment]
@koitaroh the multi-lang support one will be pushed today in a few hours. watch out! I am going to close this issue.
