### ISSUE TITLE
 Has concepts list a limit length? (Python 3.5, clarifai 2.0.17) 

### ISSUE THREAD

**Issue by Ludim** [Clarifai/clarifai-python#45]
Hello, I want to create a image from url with the next information:
`image_id = "1088078"`
`image = "http://mcdn.zulilyinc.com/media/catalog/product/145423/zu27577138_main_tm1436807694.jpg"`
`concepts = ['ca_9', 'cp_100004', 'cp_100007', 'at_11', 'at_12', 'at_18', 'at_19', 'at_21', 'at_22', 'at_23', 'at_24', 'at_25', 'at_26', 'at_27', 'at_28', 'at_29', 'at_30', 'at_31', 'at_32', 'at_36', 'at_37', 'at_38', 'at_39', 'at_40', 'at_41', 'at_42', 'at_43', 'at_45', 'at_46', 'at_49', 'at_50', 'at_51', 'at_52', 'at_53', 'at_54', 'at_55', 'at_56', 'at_57', 'at_58', 'at_98', 'at_101', 'at_102', 'at_119', 'at_120', 'at_133', 'at_134', 'at_135', 'at_136', 'at_137', 'at_138', 'at_139', 'at_140', 'at_160', 'at_161', 'at_164', 'at_170', 'at_181', 'at_183', 'at_184', 'at_185', 'at_186', 'at_187', 'at_188', 'at_189', 'at_190', 'at_202', 'at_211', 'at_212', 'at_213', 'at_215', 'at_216', 'at_217', 'at_218', 'at_219', 'at_234', 'at_236', 'at_240', 'at_242', 'at_243', 'at_244', 'at_245', 'at_246', 'at_247', 'at_249', 'at_252', 'at_254', 'at_255', 'at_257', 'at_268', 'at_269', 'at_270', 'at_271', 'at_272', 'at_273', 'at_274', 'at_275', 'at_276', 'at_277', 'at_278', 'at_279', 'at_280', 'at_281', 'at_282', 'at_283', 'at_510', 'at_521', 'at_522', 'at_738', 'at_739', 'at_740', 'at_741', 'at_742', 'at_743', 'at_744', 'at_745', 'at_804', 'at_897', 'at_898', 'at_899', 'at_909', 'at_920', 'at_927', 'at_952', 'at_959', 'oc_230', 'oc_231', 'oc_232', 'oc_233', 'oc_647', 'oc_648', 'oc_649', 'oc_650', 'oc_652', 'oc_653', 'oc_867', 'cs_100001']`

But Clarifai API returns the next message:
`Traceback (most recent call last):
  File "load-items.py", line 40, in <module>
    app.inputs.create_image_from_url(image_id=d['ItemId'], url=d['LinkToImage'], concepts=concept_by_item, allow_duplicate_url=True)
  File "/usr/local/lib/python3.5/dist-packages/clarifai/rest/client.py", line 795, in create_image_from_url
    return self.create_image(image)
  File "/usr/local/lib/python3.5/dist-packages/clarifai/rest/client.py", line 767, in create_image
    ret = self.api.add_inputs([image])
  File "/usr/local/lib/python3.5/dist-packages/clarifai/rest/client.py", line 2369, in add_inputs
    res = self.post(resource, data)
  File "/usr/local/lib/python3.5/dist-packages/clarifai/rest/client.py", line 2339, in post
    return self._requester(resource, params, 'POST', version)
  File "/usr/local/lib/python3.5/dist-packages/clarifai/rest/client.py", line 2329, in _requester
    raise ApiError(resource, params, method, res)
clarifai.rest.client.ApiError: POST inputs FAILED. code: 400, reason: Bad Request, response:<Response [400]>`

I was thinking this message is given because list concepts length is too large. In this case are 136 items (1152 bytes, using sys.getsizeof function). So, I tried to decrease the list until it worked, I found with decreasing until length was 71 elements (744 bytes).
`concepts = ['ca_9', 'cp_100004', 'cp_100007', 'at_11', 'at_12', 'at_18', 'at_19', 'at_21', 'at_22', 'at_23', 'at_24', 'at_25', 'at_26', 'at_27', 'at_28', 'at_29', 'at_30', 'at_31', 'at_32', 'at_36', 'at_37', 'at_38', 'at_39', 'at_40', 'at_41', 'at_42', 'at_43', 'at_45', 'at_46', 'at_49', 'at_50', 'at_51', 'at_52', 'at_53', 'at_54', 'at_55', 'at_56', 'at_57', 'at_58', 'at_98', 'at_101', 'at_102', 'at_119', 'at_120', 'at_133', 'at_134', 'at_135', 'at_136', 'at_137', 'at_138', 'at_139', 'at_140', 'at_160', 'at_161', 'at_164', 'at_170', 'at_181', 'at_183', 'at_184', 'at_185', 'at_186', 'at_187', 'at_188', 'at_189', 'at_190', 'at_202', 'at_211', 'at_212', 'at_213', 'at_215', 'at_216']`

I did the same with another images that I want to create and they coincided that need the same length to load in my app.

It appears that has a restrictions in limit length or size (bytes). If it is the problem, does Clarifai API accept to append new concepts to existing concepts in image id?

What do you think?

**Comment by robertwenquan** [comment]
Hi @Ludim 

sorry it took so long to respond. I verified this is no such bug. 
The possibility is either you are running into duplicate url or duplicate ID. 

You will have to parse the Exception to see what's going on excactly.

In the most recent v2.0.20 client it will prompt more verbose error message so you can tell what's going on. Please try the latest client. I am closing this issue.
