### ISSUE TITLE
Resource does not exist

### ISSUE THREAD

**Issue by anilpai** [Clarifai/clarifai-python#47]
`model = app.models.get("general-v1.3")`

outputs:

> RESULT:
> {u'status': {u'code': 11101,
>              u'description': u'Resource does not exist',
>              u'details': u"model_id 'general-v1.3' not found. Check the url of your request."}}

**Comment by Kriti007** [comment]
I am also having the exact issue.

**Comment by zeiler** [comment]
Try this out, using the model id for the general model should get you the model directly instead of searching through the models: 
```
model = app.models.get("aaa03c23b3724a16a56b629203edc62c")
```
We'll look into why you call doesn't work though.

**Comment by zeiler** [comment]
I actually that print is perfectly normal (though confusing). You can ignore it. You properly have the general model with your original call. It basically under the hood triest that string as the model id, fails, print, then tries that string to search for a model and matches then returns.

**Comment by Kriti007** [comment]
I tried passing the id, it works now! 
However, is there a way to get the model IDs(other than the general one which you just shared) so that we can pass them directly for now.

**Comment by zeiler** [comment]
Oh yeah, you can just do GET /models to see them all with curl or postman! You should see things like food, travel, general, etc. all in the response. For curl: 

```curl -H 'Authorization: Bearer {TOKEN}'  https://api.clarifai.com/v2/models```

**Comment by anilpai** [comment]
@zeiler Agreed ! I was able to use the model but I see this error message in console regularly. This hasn't been fixed yet. I will ignore the error message for now.
