### ISSUE TITLE
Can't get video prediction to work

### ISSUE THREAD

**Issue by danielmapar** [Clarifai/clarifai-python#48]
Hello Clarifai team,

I am making a simple Python3 + Tkinter + Clarifai to show the output of the API when supplying image/video files to it. However, I am facing some issues specifically with video files.

My code:

```python
class Clarifi:

	def client(self, app_id, app_secret):

		app = ClarifaiApp(app_id, app_secret)

		# get the general model
		return app.models.get("general-v1.3")

	def run_using_link(self, app_id, app_secret, link):

		return self.client(app_id, app_secret).predict_by_url(url=link);
```

If I call ```run_using_link``` with an image url I get this as an output:

<img width="1318" alt="screen shot 2017-02-27 at 10 29 05 pm" src="https://cloud.githubusercontent.com/assets/4336805/23387777/77054854-fd3d-11e6-88be-2a42e3f6f4df.png">

However, if I call passing a video (MP4) the output is:

<img width="1322" alt="screen shot 2017-02-27 at 10 29 58 pm" src="https://cloud.githubusercontent.com/assets/4336805/23387796/916a447e-fd3d-11e6-89f8-9ce20753c89d.png">

I am also facing some difficulties to understand how can I send local files using the API. Having said that, I could not find how to do video uploads with local files.

I got this code:

```python
def run_using_file(self, app_id, app_secret, file_path):

		api = ClarifaiApi(app_id, app_secret)
		return api.tag([open(file_path, "r")])
```

from another ticket: https://github.com/Clarifai/clarifai-python/issues/36

You guys can find the full source code at: https://github.com/danielmapar/ClarifaiDemo

**Comment by robertwenquan** [comment]
Oh sorry the v2 api doesn't support video as of now.
You can use the v1 api client to tag the video.

```
from clarifai.client import ClarifaiApi

api = ClarifaiApi()

api.tag_urls([video_url])
```

**Comment by robertwenquan** [comment]
@danielmapar did you figure out how to work with the video?

**Comment by danielmapar** [comment]
Yes!

It was not a problem with my code, but with my client token. I got in touch with Jared Lerner and he solved the problem.

**Comment by robertwenquan** [comment]
good to hear that. feel free to reach out if you have any question.
