### ISSUE TITLE
How to run "clarifai config" under Windows 10

### ISSUE THREAD

**Issue by arcontechnologies** [Clarifai/clarifai-python#50]
Dear,

Seems that you are missing the steps to configure with clarifai client under windows 10.

The python package installed : clarifai-2.0.20

thanks for your feedback.

**Comment by robertwenquan** [comment]
Hi @arcontechnologies 

Thanks for reporting the issue and sorry to hear it's not working correctly under Windows 10. From te symptom it should be PATH related issue if you cannot find the command. However, I will need to find a Windows machine to reproduce and see how it could work. I will get back to you as soon as I could.

**Comment by arcontechnologies** [comment]
@robertwenquan 
thanks for the feedback, I finally got it.
When installing with pip it didn't install "scripts" folder where "clarifai" file reside. So the trick was to :

1 - copy scripts folder into clarifai folder 
2 - run <Path to clarifai folder>/scripts/python clarifai config

and I was able to make a request via :

from clarifai.rest import ClarifaiApp
app = ClarifaiApp()
app.tag_files(['C:/Users/Desktop/Documents/metro.jpg'])

**Comment by robertwenquan** [comment]
@arcontechnologies glad to hear it's working for you. I will find a Windows instance to check what happens there and make the fix afterwards.

**Comment by FrankHan** [comment]
This is really important for Windows python users! Thank you @arcontechnologies!

**Comment by robertwenquan** [comment]
It will be addressed in the document of v2.0.21 
closing the ticket.

**Comment by robertwenquan** [comment]
http://clarifai-python.readthedocs.io/en/v2.0.21/install/

check the Windows section

**Comment by FrankHan** [comment]
This is nice! @robertwenquan
