### ISSUE TITLE
configuration error on windows

### ISSUE THREAD

**Issue by 1163307648** [Clarifai/clarifai-python#53]
hi I encountered the following error

E:\winpython\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\Scripts>python clarifai config
CLARIFAI_APP_ID: []: X*******************************6-e
CLARIFAI_APP_SECRET: []: K**************************wYinsz
Traceback (most recent call last):
  File "clarifai", line 167, in <module>
    main()
  File "clarifai", line 159, in main
    configure()
  File "clarifai", line 93, in configure
    setup(app_id_input, app_secret_input)
  File "clarifai", line 32, in setup
    os.mkdir(CONF_DIR)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '\\Users\\Administrator\\.clarifai'

The system can not find the specified path. : '\\ Users \\ Administrator \\. clarifai'

I checked that there is no folder named .clarifai under \\Users\\Administrator.the script clarifai fails to create .clarifai.
and there is no Environment variable “HOMEPATH” or "HOME" .is it necessary to create these variables？and  What values should these variables have?

**Comment by 1163307648** [comment]
The problem is solved. change the "HOMEPATH" from "\ Users \ Administrator " to "C:\ Users \ Administrator "

**Comment by robertwenquan** [comment]
since it's solved. I am closing the issue.
