### ISSUE TITLE
requirements.txt not found during installation of PyPI version 2.0.22 on Python 3

### ISSUE THREAD

**Issue by tyarkoni** [Clarifai/clarifai-python#55]
Installing 2.0.22 via pip results in the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

This doesn't happen on Python 2, and I've reproduced it on two separate machines (see [this build failure on travis](https://travis-ci.org/tyarkoni/pliers/jobs/237514503)). Specifying version 2.0.21 installs fine.

**Comment by robertwenquan** [comment]
Hi @tyarkoni 

Thanks for reporting the installation issue on 2.0.22. I will take a look and get back to you.

**Comment by robertwenquan** [comment]
Hi @tyarkoni 

This has been a regression in v2.0.22 and has been fixed in the latest version.
Please try `pip install clarifai` 

Sorry for the inconvenience.

**Comment by tyarkoni** [comment]
Thanks!
