### ISSUE TITLE
Cannot import name 'rest', Installation problems on Ubuntu 16.04

### ISSUE THREAD

**Issue by samhains** [Clarifai/clarifai-python#68]
I usually use conda for python package management, and was unable to get past this error

## With Conda

`which python` returns:
`/home/sam/anaconda3/envs/python352/bin/python`

`which clarifai` returns:
`home/sam/anaconda3/envs/python352/bin/clarifai`

python version 3.5.2
clarifai verison 2.0.29

```
Traceback (most recent call last):
  File "clarifai.py", line 2, in <module>
    from clarifai import rest
  File "/home/sam/Code/barnes-staff-backend/clarifai.py", line 2, in <module>
    from clarifai import rest
ImportError: cannot import name 'rest'
```

I switched to VirtualEnv and followed instructions that @robertwenquan gave on #66 exactly

## With VirtualEnv

I get a slightly different but very similar error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/Code/barnes-staff-backend/clarifai.py", line 2, in <module>
    from clarifai import rest
ImportError: cannot import name 'rest'
```

`which python` returns:
`/home/sam/Code/barnes-staff-backend/bb/bin/python`
`which clarifai` return:
`/home/sam/Code/barnes-staff-backend/bb/bin/clarifai`

python version 3.5.2
clarifai verison 2.0.29

I have tried different versions of clarifai, and using different python executables and I am having no luck at all.

**Comment by robertwenquan** [comment]
please rename your filename from `clarifai.py` to something else. Your filename `clarifai` overrides the library name `clarifai` which breaks the `clarifai.rest`. That's why it couldn't find `rest`

**Comment by samhains** [comment]
ah thats that was it :sweat_smile: , thanks

**Comment by robertwenquan** [comment]
good to hear back to you. I am closing the ticket.
