### ISSUE TITLE
Error during installing 

### ISSUE THREAD

**Issue by petriichuk** [Clarifai/clarifai-python#72]
Trying to install on latest MacOS with python3.6, getting this error

`    clang: warning: -framework Tk: 'linker' input unused [-Wunused-command-line-argument]
    In file included from _imagingtk.c:19:
    In file included from Tk/tkImaging.c:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/tk.h52:78:11: :
    fatal error: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/tk.h:78:'X11/Xlib.h' file not found
    11: fatal error: 'X11/Xlib.h' file not found
    #       include <X11/Xlib.h>#       include <X11/Xlib.h>
    
                    ^                ^
    
    1 error generated.
    1 error generated.
    /usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/_imagingtk.o build/temp.macosx-10.6-intel-3.6/Tk/tkImaging.o -L/Users/petriichuk/projects/django/petrichuk.com/petrichuk/venv/lib -L/opt/local/lib -L/usr/local/lib -L/usr/local/Cellar/freetype/2.7.1/lib -L/usr/lib -o build/lib.macosx-10.6-intel-3.6/PIL/_imagingtk.cpython-36m-darwin.so -framework Tcl -framework Tk
    clang: error: no such file or directory: 'build/temp.macosx-10.6-intel-3.6/_imagingtk.o'
    clang: error: no such file or directory: 'build/temp.macosx-10.6-intel-3.6/Tk/tkImaging.o'
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of Pillow
Command "/Users/petriichuk/projects/django/petrichuk.com/petrichuk/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/1p/lzxyybzj6qbgx4gb1bh8l81c0000gn/T/pip-build-lv3cpwre/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1p/lzxyybzj6qbgx4gb1bh8l81c0000gn/T/pip-5ihdvylb-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/petriichuk/projects/django/petrichuk.com/petrichuk/venv/include/site/python3.6/Pillow" failed with error code 1 in /private/var/folders/1p/lzxyybzj6qbgx4gb1bh8l81c0000gn/T/pip-build-lv3cpwre/Pillow/`

**Comment by petriichuk** [comment]
solved 
Solution was from [here](https://stackoverflow.com/questions/11465258/xlib-h-not-found-when-building-graphviz-on-mac-os-x-10-8-mountain-lion): 

Just put in terminal:
`https://stackoverflow.com/questions/11465258/xlib-h-not-found-when-building-graphviz-on-mac-os-x-10-8-mountain-lion`

**Comment by rok-povsic** [comment]
@petriichuk Glad you were able to solve this. Do you mean the command `ln -s /opt/X11/include/X11 /usr/local/include/X11`?

**Comment by petriichuk** [comment]
@rok-povsic yes, I put wrong text in the comment above, have edited now,
