### ISSUE TITLE
Clarifai_APP_ID is not verifying

### ISSUE THREAD

**Issue by Abby3017** [Clarifai/clarifai-python#75]

**Comment by eddiezane** [comment]
@Abby3017 sorry you ran into this issue.

Have a look at the `Py` `Predict` example [here](https://clarifai.com/developer/quick-start/).

We'll get those docs updated for the future.

**Comment by kunal732** [comment]
@Abby3017 You will need to upgrade your client. We have switched over to API Keys from appid and secret. 

Then you can rerun the `clarifai config` command to get prompted for your api key.

**Comment by Abby3017** [comment]
Thanks for your response. 
After upgrading the clarifai it worked like charm.
