### ISSUE TITLE
UnboundLocalError during load testing

### ISSUE THREAD

**Issue by larsyencken** [Clarifai/clarifai-python#76]
When we load test an internal API that calls Clarifai with a known model name, we sometimes get an `UnboundLocalError`:

```
UnboundLocalError: local variable 'model' referenced before assignment
at get (/env/lib/python3.6/site-packages/clarifai/rest/client.py:1340)
at tag_urls (/env/lib/python3.6/site-packages/clarifai/rest/client.py:144)
...(rest of backtrace in our code)
```

It appears that the client code in the `get()` method only handles 401s and 404s from your API, and silently passes out of the `except:` clause for other types of ApiError. Presumably it should just raise it instead

https://github.com/Clarifai/clarifai-python/blob/master/clarifai/rest/client.py#L1340

**Comment by larsyencken** [comment]
Since it happens during load testing, I imagine we're getting a 429 from your API in an unexpected place.

**Comment by robertwenquan** [comment]
@larsyencken thanks for opening the issue and making the fix. I've approved and merged the PR. Will incorporate this fix into the next release but it may take some time as it's a minor issue.
