### ISSUE TITLE
Is it still the main repository for clarifai python package?

### ISSUE THREAD

**Issue by benjaminrigaud** [Clarifai/clarifai-python#84]
HelloThere is a 2.1.0 version on Pypi: https://pypi.python.org/pypi/clarifai/2.1.0

But I can't find any reference to 2.1.0 on this repo.
Is there a changelog somewhere?

Regards,
Ben

**Comment by rok-povsic** [comment]
Hi @benjaminrigaud thanks for the notice, the latest changes (version 2.1.0) have been pushed to the repo.
