### ISSUE TITLE
Hey! Clarifai Python Client v2.1.0 upgrade available. Send these type of messages to error stream

### ISSUE THREAD

**Issue by lucidprogrammer** [Clarifai/clarifai-python#85]
There are scripts which depend on output. Please send these types of outputs to sys.stderr

**Comment by kunal732** [comment]
@lucidprogrammer thanks for bringing this to our attention. We're going to remove this from our standard output to prevent situations like this from happening.

**Comment by rok-povsic** [comment]
@lucidprogrammer We've removed these kinds of outputs. Please update to the latest version and tell us if you encounter any problems. Thanks.
