### ISSUE TITLE
Not an issue, but here's my resume. 

### ISSUE THREAD

**Issue by ferdavid1** [Clarifai/clarifai-python#86]
[CurrentResume.pdf](https://github.com/Clarifai/clarifai-python/files/1936247/CurrentResume.pdf)
I'm an soon-to-be new grad looking for a position in computer vision engineering. I have 4 years of research experience in applied machine learning and statistics (for biology and neuroscience) as an undergrad. This is likely not allowed, so you can close the issue and I'll disappear forever - but that is a risk I'm willing to take. 
My email is fespinosa@ucdavis.edu, please contact me if you would like to get to know me better.

**Comment by kunal732** [comment]
Ha, thanks @ferdavid1. Appreciate the novel approach. Will submit your resume internally.
