### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by sionking** [Clarifai/clarifai-python#87]
I am working on a server and my GW to internet is though proxy,
Whay there is no proxy support ?

**Comment by kunal732** [comment]
hey @sionking this is supported, we can showcase an example soon.

**Comment by sionking** [comment]
Sure since you use request session no ?
Please update :)

**Comment by rok-povsic** [comment]
@sionking You're correct, you can access the session object with `app.api.session`. Example:
```python
app = ClarifaiApp(quiet=True)
app.api.session.proxies = {'https': '...'}
```

I haven't tested this because I don't have a reliable proxy available at this moment, so I'm looking forward to your response whether this works fine.

**Comment by sionking** [comment]
Thanks but not working :(
clarifai_api.api.session.proxies = {'https': proxy}
AttributeError: 'ApiClient' object has no attribute 'session'

**Comment by rok-povsic** [comment]
@sionking I don't think you have the latest version 2.2.3 . We've added session use only recently, so please upgrade to the latest version.
