### ISSUE TITLE
Can I create custom model with video inputs?

### ISSUE THREAD

**Issue by nanjekyejoannah** [Clarifai/clarifai-python#88]
I want to create a custom model so that I can train it with video input. Is this possible atm?

**Comment by robertwenquan** [comment]
@nanjekyejoannah this might not a good channel for support question. 
please reach out to support@clarifai.com if you are having questions or problems on using the API. 

Before reaching out, feel free to check the documentation from here https://clarifai.com/developer/guide/

In short, we can not directly train on video. You will need to slice the video into frames and train from the images. Hope that helps.
