### ISSUE TITLE
app.model.predict_by_base64 does not catch ConnectionError

### ISSUE THREAD

**Issue by robmarkcole** [Clarifai/clarifai-python#92]
I've had to add to my code the following, but would be nice if this was caught by `ApiError`

```python
    def model_prediction(self, image):
        """Make a prediction based on an image."""
        try:
            response = self.model.predict_by_base64(encode_image(image))
            if response['status']['description'] == 'Ok':
                return response
        except requests.exceptions.ConnectionError:
            _LOGGER.error("ConnectionError: Is %s accessible?", CLASSIFIER)
            return None
```

**Comment by rok-povsic** [comment]
@robmarkcole I agree, the ConnectionError is an implementation detail that shouldn't be exposed by the API. I'll make a fix. Thanks for reporting this!

**Comment by rok-povsic** [comment]
@robmarkcole This has been done under version 2.4.0 that was just released.

**Comment by robmarkcole** [comment]
@rok-povsic on connection error can this be described in the error `response`? Currently I don't get a useful descriptor, as below:

```
During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-24-80e0f1af24e2> in <module>()
      2     response = general_model.predict_by_base64(encoded_string)
      3 except ApiError as exc:
----> 4     error = json.loads(exc.response.content)
      5     print(
      6         "%s error: %s", CLASSIFIER, error['status']['description'])

AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by rok-povsic** [comment]
@robertwenquan I assume this happens when testing, using a mock? `exc.response` the same object that you pass to the `response` parameter when creating `ApiError`. So if you want `.content` to be there, don't do `ApiError(..., response=None)` but pass a true (fake) response object that has this field.

Makes sense?
