### ISSUE TITLE
Install clarifai on windows

### ISSUE THREAD

**Issue by sterid** [Clarifai/clarifai-python#94]
Hello, 
Why should I download and install MS Build tools (which are about 5gb with VS) for using clarifai in python? Pls fix it and build what you need on your side.  This installation pattern is very unfriendly

**Comment by rok-povsic** [comment]
@sterid Hello, can you tell the Windows version you're using, and paste the error that occurs when installing clarifai? 

I've tried installing clarifai on a clean Windows Server 2016. I've tried both Python 2 and 3 and installed clarifai simply with `pip install clarifai`. MS Build tools was not needed to be manually installed but I think it's already present in the native system. Visual studio is definitely not needed. Windows 10 should behave the same.

If your system is missing MS Build Tools, you should be able to [install it without VS](https://stackoverflow.com/questions/42696948/how-can-i-install-the-vs2017-version-of-msbuild-on-a-build-server-without-instal).

**Comment by sterid** [comment]
Hi, @rok-povsic I've recently reinstalled OS and Clarifai is installing without any issue now. Probably previous OS was broken. I used Windows 10 with Python 3.6.6 in both cases. This case could be closed. Thx

**Comment by rok-povsic** [comment]
@sterid I'm glad it's working.
