### ISSUE TITLE
ApiError.response is None if no internet connection

### ISSUE THREAD

**Issue by robmarkcole** [Clarifai/clarifai-python#97]
An `ApiError` is thrown if the internet connection is unavailable, but `ApiError.response` is `None` in this case. Please could it be handled explicitly

**Comment by rok-povsic** [comment]
@robmarkcole Yeah, a fix was just released yesterday in 2.4.2, please upgrade.

**Comment by rok-povsic** [comment]
Ignore above, I see what you're saying.

In that case the response is None because on unavailable internet connection, no response has been received. The response object contains error fields when an error response is actually received.

**Comment by robmarkcole** [comment]
Will this behaviour be changed in an upcoming release?

**Comment by rok-povsic** [comment]
@robmarkcole There is no immediate plan of changing this behavior. I _would_ like to expand `ApiError` to have error classes such as `TimeoutApiError` and `FailureResponseApiError` etc. but this is something we have to think about.
