### ISSUE TITLE
multiprocessing bug, requests

### ISSUE THREAD

**Issue by breuerfelix** [Clarifai/clarifai-python#99]
I got a really strange problem and i wasn't able to break it down even more than that.  
this code doesn't work:
```
import multiprocessing
import requests

import clarifai.rest

def start():
    r = requests.get('https://www.github.com')
    print(str(r))

#start()
thread = multiprocessing.Process(target = start)
thread.start()
thread.join()
```

this code does work:
```
import multiprocessing
import requests

def start():
    r = requests.get('https://www.github.com')
    print(str(r))

#start()
thread = multiprocessing.Process(target = start)
thread.start()
thread.join()
```

somehow if i just call the function WITHOUT multiprocessing, it DOES work !

Do you import anything in your Lib what could break that ?

**Comment by dcirne** [comment]
@breuerfelix were you able to make it work? 

Perhaps the source is something else other than threads?

**Comment by breuerfelix** [comment]
unfortunately not.... i gave up and searched for another solution. I tried to import each of clarifais dependencies to see which one could cause the error but i had no luck.

Sad part is, i don't even get an error. The program just closes when executing the requests.get command ... I could have changed requests source code to see which line isnt able to get executed but i already wasted 4-5 hours to find out that this was the reason for my program to exit without any message. 

I still wanted to share it because this could help other people in the future and maybe, just maybe you are able to fix this :) I would be really interested in what could be the reason for that, since its a strange  behviour.

**Comment by rok-povsic** [comment]
@breuerfelix Hi, can you tell which OS, Python version and Clarifai version you're using?

I've tested your examples on Linux using the latest Clarifai version with Python 2.7 and 3.7, and both examples produce the same result (i.e. print out `<Response [200]>`).

**Comment by breuerfelix** [comment]
I am using MacOS Mojave 10.14.3

Python 3.7.2 and Clarifai 2.5.2.

Glad to know that it works on Linux, maybe someone could test it on Mac too ? Could be that i messed something else up on my laptop :)

**Comment by robertwenquan** [comment]
Hi @breuerfelix thanks for reporting the issue.
I first tried your code on Mac with `python 2.7` and `clarifai==2.5.2`. It works.

Then I managed to reproduce this with `python 3.6.5` and `clarifai==2.5.2` on my Mac.
Will update when I get more clue.

**Comment by breuerfelix** [comment]
@robertwenquan thanks for testing this out :)

So it seems to be a problem with the latest Python and clarifai version .. at least its not a problem with old versions so it's worth having a look at that :)

**Comment by rok-povsic** [comment]
@breuerfelix Hi, what you've come upon is an interesting Python 3 bug that appears in MacOS. The Python devs seem to still be in the process of figuring out the solution, see [here](https://bugs.python.org/issue33725) for more info.

There appear to be two workarounds. The first one is to do `multiprocessing.set_start_method('forkserver')` at the start of your program (note this has to be inside of a `if __name__ == '__main__':` code block. 

An example:

```python
import multiprocessing
import requests

import clarifai.rest

def start():
    r = requests.get('https://www.github.com')
    print(str(r))

if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver')

    thread = multiprocessing.Process(target=start)
    thread.start()
    thread.join()
```

Another workaround which may or may not be suited for your program would be to not use the `processing` but the `threading` module. Example:

```python
import threading
import requests

import clarifai.rest

def start():
    r = requests.get('https://www.github.com')
    print(str(r))

thread = threading.Thread(target = start)
thread.start()
thread.join()
```

**Comment by breuerfelix** [comment]
@rok-povsic this is indeed really interesting! after reading the bug tracker, it seems like even the python dev team is not able to fix it.

unfortunately threading was not an option for me. in the end i took a totally different approach on my problem. yet i wanted to share the problem cause maybe i could have been a bug in your package :)

i tried the first solution ('forkserver') and it worked like a charm ! thanks, maybe this is going to help more people in the future :)
